#!/usr/bin/env bash
#MISE description="Build/compile the diff v1.0.0 PDF."
#MISE dir="{{ config_root }}/tex/"
#MISE depends=["diff-v1.0.0:create"]
#MISE sources=["diff-v1.0.0.tex"]
#MISE outputs=["diff-v1.0.0.pdf"]
CURRENT_LATEST=$(git describe --tags --abbrev=0 2>/dev/null)
[[ "$CURRENT_LATEST" != "v1.0.0" ]] && { echo "diff-v1.0.0: skipping, newer revision exists"; exit 0; }
latexmk -pdf -g -f -silent -recorder- diff-v1.0.0.tex
