#!/usr/bin/env bash
#MISE description="Update the bibliography for review response v2026.3.0."
#MISE dir="{{ config_root }}/tex/"
#MISE sources=["review-v2026.3.0.tex"]
#MISE outputs=["review-v2026.3.0.bib"]
CURRENT_LATEST=$(git describe --tags --abbrev=0 2>/dev/null)
[[ "$CURRENT_LATEST" != "v2026.3.0" ]] && { echo "review-v2026.3.0: skipping, newer revision exists"; exit 0; }
bibfish -c 'cite,citet,citep,citeA,printpartbibliography' -f review-v2026.3.0.tex ../main-ref.bib review-v2026.3.0.bib
