---
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  MISE_EXPERIMENTAL: true
  MISE_ENV: ci
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
      - run: mise run ci:build
      - if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: build-logs
          path: tex/*.log
      - run: mise run package
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: paper-assets
          path: |
            tex/main.pdf
            tex/diff*.pdf
            tex/review*.pdf
            tex/paper.zip
          if-no-files-found: error
